name: PACKAGE222
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    branches:
      - main
    paths-ignore:
      - documentation/**
      - '**/README.md'
      - '**/README_zh.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - documentation/**
      - '**/README.md'
      - '**/README_zh.md'
jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.legs.RTT_PACKAGE }}
    strategy:
      fail-fast: false
      matrix:
       legs:
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MS5611", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MAX31865", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_VL53L0X", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_INA260", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MAX30102", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_INA226", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LIS2DH12", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_HS300X", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ZMOD4410", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ISL29035", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MMC3680KJ", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_QMP6989", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_BALANCE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SHT2X", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SHT3X", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AD7746", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ADT74XX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MAX17048", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AS7341", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CW2015", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ICM20608", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_PAJ7620", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_STHS34PF80", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_GT9147", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_GT1151", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_GT917S", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_GT911", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FT6206", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FT5426", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FT6236", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_XPT2046_TOUCH", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_REALTEK_AMEBA", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_STM32_SDIO", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ESP_IDF", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_BUTTON", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_PCF8574", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SX12XX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SIGNAL_LED", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LEDBLINK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LITTLED", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LKDGUI", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_NRF5X_SDK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_NRFX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_K210_SDK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_KENDRYTE_SDK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_INFRARED", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MULTI_INFRARED", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AGILE_BUTTON", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AGILE_LED", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AT24CXX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MOTIONDRIVER2RTT", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_PCA9685", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ILI9341", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_I2C_TOOLS", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_NRF24L01", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_RPLIDAR", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AS608", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_RC522", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_WS2812B", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_EMBARC_BSP", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_EXTERN_RTC_DRIVERS", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MULTI_RTIMER", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MAX7219", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_BEEP", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_EASYBLINK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_PMS_SERIES", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CAN_YMODEM", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LORA_RADIO_DRIVER", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_QLED", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AGILE_CONSOLE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LD3320", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_WK2124", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LY68L6400", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_DM9051", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SSD1306", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_QKEY", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_RS485", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_RS232", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_NES", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_VIRTUAL_SENSOR", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_VDEVICE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SGM706", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_STM32WB55_SDK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_RDA58XX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LIBNFC", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MFOC", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_TMC51XX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_TCA9534", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_KOBUKI", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ROSSERIAL", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MICRO_ROS", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MCP23008", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_BLUETRUM_SDK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MISAKA_AT24CXX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MISAKA_RGB_BLING", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LORA_MODEM_DRIVER", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SOFT_SERIAL", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MB85RS16", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_RFM300", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_IO_INPUT_FILTER", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_RASPBERRYPI_PICO_SDK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LRF_NV7LIDAR", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_AIP650", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FINGERPRINT", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SPI_TOOLS", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LIBANN", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_NNOM", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ONNX_BACKEND", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ONNX_PARSER", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_TENSORFLOWLITEMICRO", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ELAPACK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ULAPACK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_QUEST", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_NAXOS", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FIRE_PID_CURVE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_UKAL", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_KERNEL_SAMPLES", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FILESYSTEM_SAMPLES", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_NETWORK_SAMPLES", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_PERIPHERAL_SAMPLES", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CMATRIX", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SL", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CAL", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ACLOCK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_THREES", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_2048", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SNAKE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_TETRIS", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_DONUT", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_COWSAY", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MORSE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LIBCSV", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_OPTPARSE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FASTLZ", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MINILZO", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_QUICKLZ", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LZMA", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MULTIBUTTON", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_FLEXIBLE_BUTTON", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CANFESTIVAL", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ZLIB", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MINIZIP", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_HEATSHRINK", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_DSTR", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_TINYFRAME", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_KENDRYTE_DEMO", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_DIGITALCTRL", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_UPACKER", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_UPARAM", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_HELLO", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_VI", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_KI", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_ARMv7M_DWT", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CRCLIB", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_LWGPS", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_STATE_MACHINE", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_DESIGN_PATTERN", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CONTROLLER", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_PHASE_LOCKED_LOOP", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_MFBD", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SLCAN2RTT", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_SOEM", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_QPARAM", RTT_PACKAGE_CMD: "core_mark"}
        - {RTT_PACKAGE: "CONFIG_PKG_USING_CorevMCU_CLI", RTT_PACKAGE_CMD: "core_mark"}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: RT-Thread/rt-thread
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Tools
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -qq install gcc-multilib libncurses5-dev scons
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y qemu-system-arm
          sudo python -m pip install --upgrade pip -qq
          pip install requests -qq
          git config --global http.postBuffer 524288000
          python -c "import tools.menuconfig; tools.menuconfig.touch_env()"
          echo "RTT_ROOT=${{ github.workspace }}" >> $GITHUB_ENV
          echo "RTT_CC=gcc" >> $GITHUB_ENV
      - name: Install Arm ToolChains
        shell: bash
        run: |
          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
          /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version
          echo "RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin" >> $GITHUB_ENV
      - name: Bsp Scons Compile
        if: ${{ success() }}
        shell: bash
        env:
          RTT_BSP: qemu-vexpress-a9
        run: |
          source ~/.env/env.sh
          scons --pyconfig-silent -C bsp/$RTT_BSP
          sed -i "s/# ${{ matrix.legs.RTT_PACKAGE }} is not set/${{ matrix.legs.RTT_PACKAGE }}=y/g" bsp/$RTT_BSP/.config
          sed -i "s/# CONFIG_PKG_USING_RTT_AUTO_EXE_CMD is not set/CONFIG_PKG_USING_RTT_AUTO_EXE_CMD=y/g" bsp/$RTT_BSP/.config
          scons --pyconfig-silent -C bsp/$RTT_BSP
          sed -i "s/CONFIG_COREMARK_ITERATIONS=3600/CONFIG_COREMARK_ITERATIONS=36000/g" bsp/$RTT_BSP/.config
          
          sed -i "s/CONFIG_RTT_CMD_1_STR=\"version\"/CONFIG_RTT_CMD_1_STR=\"core_mark\"/g" bsp/$RTT_BSP/.config
          
          scons --pyconfig-silent -C bsp/$RTT_BSP
          cat bsp/$RTT_BSP/.config
          pushd bsp/$RTT_BSP && pkgs --update && popd
          scons -C bsp/$RTT_BSP
          cd bsp/qemu-vexpress-a9
          ls
          sudo nohup ./qemu-nographic.sh > cmd3.out 2>&1 &
          sleep 100
          cat cmd3.out
